# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"
a=s.split()
print(a)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742
txt="the diameter of {} is {} kilometers".format(planet,diameter)
print(txt)

the diameter of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
a=d['k1'][3]['tricky'][3]['target'][3]


hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [11]:
import numpy as np
array=np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
import numpy as np
array=np.ones(10)
print(array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## 5. Create an array of all the even integers from 20 to 35

In [13]:
import numpy as np
array=np.arange(20,35,4)
print(array)

[20 24 28 32]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [14]:
import numpy as np
matrix=np.arange(0,9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [15]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
con=np.concatenate([a,b])
print(con)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [17]:
import pandas as pd
data=[['Ben',20],['Kevin',15],['Gwen',10]]
df=pd.DataFrame(data,columns=['Name','Age'])         
print (df)                                                       

    Name  Age
0    Ben   20
1  Kevin   15
2   Gwen   10


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [18]:
import pandas as pd
date=pd.data_range(start='01-01-2023',end='02-10-2023')
print(date)

AttributeError: ignored

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [19]:
import pandas as pd
lists=[[1,'aaa',22],[2,'bbb',25],[3,'ccc',24]]
df=pd.DataFrame(lists,columns=['SI.NO','Name','Register number'])
print(df)

   SI.NO Name  Register number
0      1  aaa               22
1      2  bbb               25
2      3  ccc               24
